### ISSUE TITLE
dcc.Link or dcc.Location isn't firing callbacks for IE 11

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#113]
![image](https://user-images.githubusercontent.com/1280389/33154852-596c0f18-cfb9-11e7-900c-65e7e6ad2117.png)

originally reported in https://community.plot.ly/t/multi-page-dash-app-internet-explorer-issue/6206/3

**Comment by ned2** [comment]
I believe the issue is that IE does not support the `Event` constructor, which `dcc.Link` uses to trigger a `pushstate` event. This in turn means that the `dcc.Location` listener will never pick it up.

This [Stack Overflow post](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work) links to a MSDN page which includes a polyfill for `CustomEvent` as a workaround.
