### ISSUE TITLE
callbacks watching dcc.Location's url.pathname fire twice on first page load  

### ISSUE THREAD

**Issue by ned2** [plotly/dash-core-components#138]
When a callback targets dcc.Location's url.pathname, on the first page load (but not on the app load), I'm seeing that the callback is fired twice. The first time the `pathname`  Input gets the value `None`, then on the second time it gets the correct current value from the URL. 

Most of the time I'm comparing `pathname` against some string, so nothing bad happens and then the callback fires again and behaves correctly. However I can certainly imagine a scenario when the assumption that `pathname` is a string will make things break. Not to mention it's a little confusing when debugging.

**Comment by mjclawar** [comment]
This may be related to https://github.com/plotly/dash/issues/133 and https://github.com/plotly/dash-renderer/issues/24. (See specifically @chriddyp's comment here https://github.com/plotly/dash/issues/133#issuecomment-330714608). 
 
We addressed it for our Dash applications by adding `assert isinstance(pathname, str)` so that the first request breaks with `pathname` as `None`. It unfortunately does cause the code to break, but at least it breaks immediately in the first callback that uses `pathname`, and then Dash handles the "correct" render in the request made immediately after the 500 error.

**Comment by chriddyp** [comment]
Yeah, this is sort of "intentional" although it is confusing. I think I explained it in my comments but another solution is to return with the loading state with:
```
if pathname is None:
    return 'Loading...'
```

I'm going to close this for now as this behaviour is pretty deeply ingrained in dash's front-end.

**Comment by ned2** [comment]
Yep for sure. I hadn't seen the discussion where you explain that, but it makes sense. 

I think my preference for handling it (but obviously depends on the context) is to throw an exception for that request. If #190 goes in, then it's an even cleaner strategy.

**Comment by pope1ni** [comment]
So I bumped into this double triggering of callbacks and worked around it with an intermediate callback that did nothing. I didn't even need to raise `PreventUpdate` where the values of `pathname`, `search` or `href` were `None`.

Perhaps my attached simple example will be of use to someone: [location-double-callback-workaround.py](https://github.com/plotly/dash-core-components/files/1974103/location-double-callback-workaround.txt)

Slightly related to this, I was messing around with query strings to perform actions, and found that I needed to change `href` and not `pathname` so that I could clear query strings when the action had been performed. This seemed to make things more prone to callbacks executing multiple times and I needed to use `href` as an input rather than `pathname` to order my callbacks correctly. This workaround also seemed to avoid extra callbacks in this case.
