### ISSUE TITLE
`return {}` doesn't work for dcc.Graph?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#260]
See commuity discussion here: https://community.plot.ly/t/returning-an-empty-figure/12500/2

**Comment by chriddyp** [comment]
another one here: https://community.plot.ly/t/help-once-set-the-graph-return-none-the-graph-wont-update-anymore-even-when-get-new-data/12925

**Comment by rmarren1** [comment]
I am getting this in some apps too.

A front-end exception is thrown on this line:
https://github.com/plotly/dash-core-components/blob/de74f625e85ada15d01dbbdc780cda864f773a9b/src/components/Graph.react.js#L83

giving this vague error:
![image](https://user-images.githubusercontent.com/10272301/44734755-a09abd00-aab8-11e8-9ff7-5cc2ce0bcef9.png)

I think this is just because `figure.data` is undefined and `pluck` tries to access the `type` attribute.

I think this can be fixed for free when we fix https://github.com/plotly/dash/issues/355

**Comment by rmarren1** [comment]
Some more reports:
https://community.plot.ly/t/javascript-error-fantasy-land-map-undefined/9863

https://community.plot.ly/t/problem-with-dash-app-fantasy-land-map/9797

https://community.plot.ly/t/cannot-read-property-fantasy-land-map-of-undefined-dash-datatable-updating-table-with-dropdowns/12958 / https://stackoverflow.com/questions/51992151/cannot-read-property-fantasy-land-map-of-undefined-dash-datatable-updating-tab <-- not sure about this one, as it does not use `Graph`

**Comment by rmarren1** [comment]
Released in dash-core-components==0.28.1
