### ISSUE TITLE
RangeSlider: out-of-range labels

### ISSUE THREAD

**Issue by TahiriNadia** [plotly/dash-core-components#517]
if you put labels outside the slider range, they are still drawn, but they shouldn’t be
see here FYI https://github.com/plotly/dashR/issues/80#issue-430575656

### Example:
```
dccRangeSlider(
    marks=as.list(setNames(c(paste("Label", -5:6)), -5:6)),
    min=-5,
    max=6,
    value=list(-3, 4)
)
```

![Screen Shot 2019-04-10 at 10 28 23 AM](https://user-images.githubusercontent.com/19578926/55890938-a04fbd80-5b81-11e9-9adc-911e16d6f76a.png)

**Comment by alexcjohnson** [comment]
Ah, the fact that the labels in that image overlap the box they're in seems like a bad thing. But what bothered me more in that dashR discussion was what you originally had - if your range is -5 to 6 and you have labels at values beyond 6:

> #### _Code:_
> ```{r}
> library(dashCoreComponents)
> 
> dccRangeSlider(
>     marks=c(paste("Label", -5:6)),
>     min=-5,
>     max=6,
>     value=list(-3, 4)
> )
> ```
> 
> #### _Result:_
> ![Screen Shot 2019-04-08 at 1 37 07 PM](https://user-images.githubusercontent.com/19578926/55744836-dcf5aa80-5a03-11e9-9655-f9e0366904da.png)
> 

In that image, "Label 1" is at a value of 6, and that should be the last one drawn. The rest should (I think) simply be ignored, rather than get drawn at inaccessible locations. The alternative would be to automatically extend the range to include all defined labels, but I feel like there's a use case for "here are all the possible labels" and sometimes restricting the range to a subset of that without needing to also filter the labels.

**Comment by alexcjohnson** [comment]
@TahiriNadia was this closed on purpose?

**Comment by TahiriNadia** [comment]
I'm thinking it was done? But it's not the case, I reopen it. Thank you @alexcjohnson for this comment.
