### ISSUE TITLE
GET http://127.0.0.1:8000/_dash-component-suites/dash_core_components/highlight.pack.js?v=1.0.0&m=1563222892 net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by dipanjanMukherjee** [plotly/dash-core-components#583]
Hi,
I am trying to run a dash app as a django module. It's throwing an error citing highlight.pack.js not found.
![image](https://user-images.githubusercontent.com/29127871/61249217-596df700-a772-11e9-8362-97e31e10e3f9.png)
I have tried adding this as external_scripts parameter   {'src': 'https://cdn.jsdelivr.net/npm/highlightjs@9.12.0/highlight.pack.js'}, using which it's loading in the browser source 
![image](https://user-images.githubusercontent.com/29127871/61249404-c84b5000-a772-11e9-9338-95f1d471b5d9.png)
but it's still throwing that same error
![image](https://user-images.githubusercontent.com/29127871/61249445-de591080-a772-11e9-9e89-559782421729.png)
Thanks in advance!!

**Comment by alexcjohnson** [comment]
I'm not sure what it means to run as a django module, does it work to run the app by itself?

**Comment by dipanjanMukherjee** [comment]
@alexcjohnson Sorry I meant to say trying to run it as an application inside a django project. I have tried running one standalone example dash apps and it ran fine.

**Comment by alexcjohnson** [comment]
It looks like you're getting a 404 from `/_dash-update-component` as well, which is the one that processes callbacks. But somehow `/_dash-dependencies` and `/_dash-layout` succeed?

Dash is built on Flask, and having Flask and Django side-by-side is a little funny. There may be ways to do it all inside Django, otherwise the options I'm aware of are (1) have something lower-level like WSGI discriminate on URLs, like [this quora answer](https://www.quora.com/Is-using-both-Django-and-Flask-in-the-same-project-a-good-idea-or-will-it-make-the-app-slow), or (2) there's a django fork of dash https://pypi.org/project/django-plotly-dash/ - that's not made by Plotly though and I haven't used it, so YMMV.

**Comment by dipanjanMukherjee** [comment]
Hi @alexcjohnson Thanks a lot for your help. I tried to run dash apps inside a normal Flask app and it ran fine. It is simpler that way against trying WSGI discriminate on URLs. Closing this issue for now.
