### ISSUE TITLE
Colorbar does not update correctly when updating a dcc.Graph

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-core-components#702]
See the original community post https://community.plot.ly/t/render-colorbar-issues/31293 and the test repo https://github.com/TedHaley/bugs reproducing the issue. Basically, two datasets with different data ranges, when switching between the two the colorbar gets stuck at the same data range and therefore the colors are not what they should be. In the demo app, try switching from `plot 2` to `plot 1` and from `blank` to `plot 1`. Don't know whether dcc is the right place for this or if I should open an issue also in `plotly.js` (but the two figures look good independently, it's just the update which does something weird).

**Comment by alexcjohnson** [comment]
Here's the same thing as a codepen: https://codepen.io/alexcjohnson/pen/JjjwBKE?editors=0010
newplot@1 -> react@0 is different from newplot@0
So it's a plotly.js bug - I'm going to file it with https://github.com/plotly/plotly.js/issues/4337, which describes a slightly different situation but I suspect the underlying cause is the same
Thanks @TedHaley!

**Comment by alexcjohnson** [comment]
Oh actually it may be exactly the same thing...

**Comment by chriddyp** [comment]
It looks like  this issue was closed in https://github.com/plotly/plotly.js/issues/4337, so I'm assuming we can close here.
