### ISSUE TITLE
slider tooltip.always_visible doesn't position properly

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/dash-core-components#751]
If I put a slider into a div that has overflow-y=scroll, then the tooltip doesn't scoll with the slider

![Screenshot from 2020-02-06 13-05-47](https://user-images.githubusercontent.com/41019918/73965394-10ce8480-48e2-11ea-8a0a-4f9eda92a652.png)

```python
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash(
    __name__,
)


app.layout = html.Div([
    html.Div([
        html.Div(dcc.Slider(
            min=0,
            max=100,
            value=65,
            tooltip={'always_visible':True, 'placement':'bottom'}
        ),
        style=dict(height=100))
    ]*5,
    style=dict(maxHeight=300, overflowX='scroll'))
])


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by wbrgss** [comment]
possible related to react-component/slider/issues/374

**Comment by alb-erandelcastillo** [comment]
Since dcc.Slider is calling the react tooltip API, what would be the correct container to set for the tooltip when using getTooltipContainer?

**Comment by alb-erandelcastillo** [comment]
Since dcc.Slider is calling the react tooltip API, what would be the correct container to set for the tooltip when using getTooltipContainer?

**Comment by wbrgss** [comment]
There is a fix here in the original/official version of this repo: https://github.com/ant-design/ant-design/pull/16717. We could make a PR onto react-component/slider upstream or try to migrate `dcc.Slider` to the original (https://github.com/ant-design/ant-design/tree/master/components/slider) (cc @chriddyp if you were planning to take a look at this)

**Comment by wbrgss** [comment]
A short term fix would be to document around it with the suggestion here https://github.com/react-component/slider/issues/374#issuecomment-426086672

> getTooltipContainer works as long as the slider has a parent that has position relative

**Comment by jdamiba** [comment]
I'm currently taking a look at this. This is a non-exhaustive list of some things I'll want to figure out:

- [ ] figure out what combination of css rules is leading to this
- [ ] identify a combination of css rules that lead to the desired behavior - presumably the tooltip should only be visible when parent slider is visible and the tooltip should scroll with the parent slider has the `overflow=y` style
- [ ] understand how this bug was fixed in the ant-design component
- [ ] figure out how to update `dcc_slider` to implement the desired behavior - patch dcc_slider or migrate it entirely to another implementation?
