### ISSUE TITLE
url parameters are not available in `dcc.Location`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#81]
we're only sending the `window.location.pathname` (https://github.com/plotly/dash-core-components/blob/master/src/components/Location.react.js#L36) but we could send an object of `window.location.search` (https://stackoverflow.com/questions/5448545/how-to-retrieve-get-parameters-from-javascript)

as reported in https://community.plot.ly/t/get-url-with-get-parameters/5878/1

**Comment by mjclawar** [comment]
@chriddyp is it OK if I take this one at some point in the next week? We've run into multiple situations where it would be very helpful. 

Do you have any thoughts on changing the `Link` to support `window.location.search` as well?

As a general question: Are there contribution guidelines for this repo (e.g., PRs, building, testing) hiding anywhere? Is it OK to just change the `src` directory, add relevant tests, and then submit a PR when the issue is addressed?

Thanks!

**Comment by chriddyp** [comment]
@mjclawar  - that would be great!

There are not any contributing guidelines yet, so here is a summary:
### Testing
- We have integration tests that start a dash app and run a selenium, see https://github.com/plotly/dash-core-components/blob/c898d75a1a189943bcf92bc73b95bd08432ddd7d/test/test_integration.py#L147
- We have image tests - these tests take a snapshot of the screen _during_ an integration test and can be used instead of tedious testing of each expected out (so long as you display your outputs on the screen). Here's an example: https://github.com/plotly/dash-core-components/blob/c898d75a1a189943bcf92bc73b95bd08432ddd7d/test/test_integration.py#L198
- I recommend using `import ipdb; ipdb.set_trace()` to set breakpoints while running these selenium tests, especially when trying to do complex selenium things. selenium isn't super well documented. in fact, you can use this workflow to write your test entirely in the console, and then paste the working commands back into the actual testing code
- These integration tests are awesome because you can test the actual behaviour in the Python dash code
- We don't have any tests for `Link` and how `Link` works with `Location`. It's definitely time to add them.

### Developing
- `npm run prepublish` will generate the JS bundle and the `metadata.json` file that's required for generating the python components
- I usually run it with a file watcher, like `$ ag -l --js | entr npm run prepublish`
- Make sure to set `app.scripts.config.serve_locally` and `app.css.config.serve_locally=True` if you are working on an app in development

### Releasing
- It'd be helpful, at the end of the PR, for you to bump the version number appropriately and update the `CHANGELOG.md` file
- It's also really helpful for me in reviewing PRs if there are screenshots / GIFs of the new behaviour (On mac, I use LICEcap https://www.cockos.com/licecap/ all the time)

### This particular component
- `Link` and `Location` are actually kind of weird because they send messages to each other through the window events as there is no other way for the `Location` component to be aware of a `pushState` event. See https://github.com/plotly/dash-core-components/blob/master/src/components/Link.react.js#L17 and https://github.com/plotly/dash-core-components/blob/master/src/components/Location.react.js#L39-L44
- As you mention, it seems like `Link` should support `window.location.search` as well
- I'm not sure if we should do a new property like `search` to match the `window.location.search` API or just patch the existing `pathname` property to include `search`. Something to consider - are there other properties in `window.location` that would be helpful to expose? If so, maybe we should make it a new property. Another thing to consider - does having both properties cause conflicts (what happens if both properties are supplied but one property is inconsistent with the other) or cause otherwise unnecessary complication in the code?

**Comment by mjclawar** [comment]
Thanks for the contribution notes. Would love to get more involved in this ecosystem you've built as we've started to become pretty heavy users of Dash!

#### This particular component
Makes sense on the messages via window events, although you could patch that as a special redux action (not necessarily arguing for that).

`pathname` and `search` should be separate properties in order to match the `window.location` browser API. Just concatenating them would break code for us based on parsing the current pathname. To that end, should probably add a `hash` property as well. This way, you can make updates without having your entire app necessarily update. One thing we quickly noticed about using hashes through the `pathname` currently is that the entire app would update since we had to route most of the business logic through `pathname` to allow for sharing/saving - but there was no way to avoid that.

What do you mean by the properties being inconsistent with the other? That should be something handled by the Dash user, right? A sample use case would be something like being able to pass along extra user information of indeterminate shape without using sessions/cookies/creating unwieldy pathnames. By using `pathname`, `hash` and `search` separately, you can assemble the entire relative url and make optimizations about which pieces on the page rerender.

**Comment by chriddyp** [comment]
> although you could patch that as a special redux action (not necessarily arguing for that).

This library actually doesn't have any redux, each component is completely standalone. So, to do this the redux way would require patching the [`dash-renderer`](https://github.com/plotly/dash-renderer) project (which manages the handles the API calls and the reactive updates between components).

> should probably add a hash property as well. This way, you can make updates without having your entire app necessarily update

Yeah, that's pretty interesting. I added a `refresh` property to `Location` that you might be able to use to prevent page reload. But using a hash is definitely the better, more semantic way to do this. Using this as a way to save app state is really interested, I'm excited to see what we can do here.

> What do you mean by the properties being inconsistent with the other? That should be something handled by the Dash user, right?

A simple case would be if someone had two `Output` callbacks and one updated `href` and the other updated `hash`. But, as you say, this should just be handled by the Dash user.

> By using pathname, hash and search separately, you can assemble the entire relative url and make optimizations about which pieces on the page rerender.

Yeah, that sounds right. I think we should also add `href` so that users can get _everything_ at once if they want it.

***

Thanks again for opening up the discussion and specing things out before engineering :)

**Comment by mjclawar** [comment]
> I added a refresh property to Location that you might be able to use to prevent page reload

Page reload is one thing, but avoiding a refresh doesn't prevent all of the callbacks from firing when you use the pathname to pass information. Learned that from the browser melting down when I clicked on a couple of links quickly on a Dash app with a bunch of maps.

> Thanks again for opening up the discussion and specing things out before engineering :)

Discussion *is* engineering :smile: 

Will take a stab at this in the next few days. I don't have a ton of selenium experience (mostly use Jest + enzyme), but assuming that's at least an easy setup.

**Comment by chriddyp** [comment]
> What do you mean by the properties being inconsistent with the other? That should be something handled by the Dash user, right?

I finally remember what I was thinking here. Right now, Dash callbacks can only update a single component attribute ("output").

So, if we are updating two location properties like `path` and `hash` based off of the same input, `href` and `path` will get updated one after the other, in no particular order.

i.e. it could be `/state-1`  → `/state-1#update-2`  → `/state-2#update-2`

The dash-developer might consider `/state-1#update-2` but right now dash would have to cycle through that state to get to the final state of `/state-2#update-2`. 

While this could catch some dash developer's off-guard, there are two workarounds:
1 - They can just update `href` instead
2 - Eventually, we'll likely support callbacks that update multiple `Outputs`, in which case they could just udpate `href` and `path` within the same callback.

Given those workarounds, we're still 👍  to continue here

**Comment by mjclawar** [comment]
Submitted https://github.com/plotly/dash-core-components/pull/131. Let me know if I missed anything from the build process or need to make any changes.
